_namespace = "github.com/rur/good/_baseline/page"
_page = "newpage"
_template = "page/templates/base.html.tmpl"
_handler = "hlp.BindEnv(page.BaseHandler)"
_doc = "Base HTML template for newpage page"
_uri = "/newpage"

    [[content]]
    _name = "newpage-placeholder"
    _default = true
    _doc = "Placeholder page"
    _path = "/newpage"
    _template = "page/newpage/templates/placedholder.html.tmpl"
    _handler = "env.Bind(bindResources(placedholderHandler))"
