package main

import (
	"github.com/rur/good/baseline/routes_test/page"
	"github.com/rur/treetop"

	"github.com/rur/good/baseline/routes_test/page/example"
	"github.com/rur/good/baseline/routes_test/page/intro"
	"github.com/rur/good/baseline/routes_test/page/trivial"
)

// Code generated by go generate; DO NOT EDIT.

func registerPages(hlp page.Helper, exec treetop.ViewExecutor) {
	// register pages
	example.Routes(hlp, exec)
	intro.Routes(hlp, exec)
	trivial.Routes(hlp, exec)
}
