_namespace = "github.com/rur/good/_baseline/site"
_page = "example"
_template = "page/templates/base.html.tmpl"
_handler = "hlp.BindEnv(page.BaseHandler)"
_doc = "Base HTML template for example page"
_uri = "/example"

    [[content]]
    _name = "example-placeholder"
    _default = true
    _doc = "Placeholder page"
    _path = "/example"
    _template = "page/example/templates/placedholder.html.tmpl"
    _handler = "env.Bind(bindResources(placedholderHandler))"
