package newpage

import (
	"github.com/rur/good/baseline/page_test/page"
	"github.com/rur/treetop"
)

func Routes(hlp page.Helper, exec treetop.ViewExecutor) {

	// Code generated by go generate; DO NOT EDIT.

	placeholder := treetop.NewView(
		"::placeholder::",
		treetop.Noop,
	)

	hlp.HandleGET("/newpage",
		exec.NewViewHandler(placeholder).PageOnly())

}
