_ref = "newpage"
_template = "page/templates/base.html.tmpl"
_doc = "Base HTML template for newpage page"
_uri = "/newpage"
_handler = 'hlp.BindEnv(page.GetBaseHandler("newpage Page"))'

    [[nav]]
    _ref = "newpage-nav"
    _default = true

    [[content]]
    _ref = "newpage-landing"
    _default = true
    _doc = "Landing content view for the newpage page URI"
    _method = "GET"
    _path = "/newpage"

    [[scripts]]
    _ref = "site-scripts"
    _default = true
    _doc = "Include sitewide script footer"
    _template = "page/templates/scripts.html.tmpl"
    _handler = "treetop.Noop"
