package trivial

import (
	"github.com/rur/good/baseline/routes_test/page"
	"github.com/rur/treetop"
)

func Routes(hlp page.Helper, exec treetop.ViewExecutor) {

	// Code generated by go generate; DO NOT EDIT.

	trivialPage := treetop.NewView(
		"page/trivial/templates/trivial-page.html.tmpl",
		hlp.BindEnv(bindResources(trivialPageHandler)),
	)

	hlp.Handle("/trivial",
		exec.NewViewHandler(trivialPage).PageOnly())

}
