_ref = "example"
_template = "page/example/templates/example.html.tmpl"
_handler = "hlp.BindEnv(bindResources(exampleHandler))"
_doc = "Base HTML template for example page"
_uri = "/example"

    [[site-nav]]
    _ref = "main-nav"
    _default = true
    _template = "page/templates/nav.html.tmpl"
    _handler = "hlp.BindEnv(page.SiteNavHandler)"

    [[content]]
    _ref = "example-placeholder"
    _default = true
    _doc = "Placeholder page"
    _partial = true
    _path = "/example"
    _template = "page/example/templates/content/placeholder.html.tmpl"
    _handler = "hlp.BindEnv(bindResources(placeholderHandler))"

        [[content.form]]
        _ref = "placeholder-form"
        _default = true
        _doc = "Placeholder form"
        _fragment = true
        _method = "POST"
        _path = "/example/form"
        _template = "page/example/templates/content/placeholder.html.tmpl"
        _handler = "treetop.Constant(\"TODO\")"

    [[content]]
    _ref = "alternative-content"
    _doc = "Alaternative Content Page"
    _path = "/example/alt"
    _template = "page/example/templates/content/placeholder.html.tmpl"
    _handler = "hlp.BindEnv(bindResources(placeholderHandler))"

    [[content]]
    _ref = "other-content"
    _doc = "other Content Page"
    _path = "/example/other"

    [[scripts]]
    _ref = "site-scripts"
    _default = true
    _template = "page/templates/scripts.html.tmpl"
    _handler = "treetop.Noop"
