_ref = "example"
_template = "page/templates/base.html.tmpl"
_handler = 'hlp.BindEnv(page.GetBaseHandler("Routes Test - example page"))'
_doc = "Base HTML template for example page"
_uri = "/example"

    [[nav]]
    _ref = "main-nav"
    _default = true

    [[content]]
    _ref = "example-placeholder"
    _default = true
    _doc = "Placeholder page"
    _partial = true
    _path = "/example"
    _handler = '''treetop.Constant(struct{
        Form interface{}
    }{
        Form: struct{FormError string}{
            FormError: "This is a test",
        },
    })'''

        [[content.form]]
        _ref = "placeholder-form"
        _default = true
        _doc = "Placeholder form"
        _fragment = true
        _method = "POST"
        _path = "/example/form"

            [[content.form.form-error]]
            _ref = "basic-form-error"
            _doc = "Format and display a form error message"
            _default = true

    [[content]]
    _ref = "alternative-content"
    _doc = "Alaternative Content Page"
    _path = "/example/alt"

    [[content]]
    _ref = "settings-layout"
    _doc = "Settings page layout"

        [[content.tabs]]
        _ref = "settings-tabs"
        _doc = "Tabs for the settings page content"
        _default = true
        _handler = 'treetop.Constant("Hello World")'

        [[content.settings]]
        _ref = "general-settings"
        _doc = "General settings area"
        _path = "/example/settings"
        _partial = true

        [[content.settings]]
        _ref = "advanced-settings"
        _doc = "Advanced settings area"
        _path = "/example/advanced-settings"
        _partial = true

            [[content.settings.settings-form]]
            _ref = "update-advanced-settings"
            _doc = "Accept update to advanced settings and show result"
            _path = "/example/advanced-settings/submit"
            _includes = ["basic-form-error"]
            _fragment = true
            _method = "POST"

                [[content.settings.settings-form.form-error]]

    [[scripts]]
    _ref = "site-scripts"
    _default = true
    _template = "page/templates/scripts.html.tmpl"
    _handler = "treetop.Noop"
