package example

import (
	"github.com/rur/good/baseline/scaffold_test/page"
	"github.com/rur/treetop"
)

func Routes(hlp page.Helper, exec treetop.ViewExecutor) {

	// Code generated by go generate; DO NOT EDIT.

	example := treetop.NewView(
		"page/templates/base.html.tmpl",
		hlp.BindEnv(page.GetBaseHandler("example Page")),
	)

	// [[content]]
	examplePlaceholder := example.NewDefaultSubView(
		"content",
		"page/example/templates/placeholder.html.tmpl",
		treetop.Constant("example"),
	)

	// [[nav]]
	example.NewDefaultSubView(
		"nav",
		"::empty::",
		treetop.Noop,
	)

	// [[scripts]]
	example.NewDefaultSubView(
		"scripts",
		"::empty::",
		treetop.Noop,
	)

	hlp.HandleGET("/example",
		exec.NewViewHandler(examplePlaceholder).PageOnly())

}
