package main

import (
	"github.com/rur/good/baseline/page/page"
	"github.com/rur/treetop"

	"github.com/rur/good/baseline/page/page/example"
	"github.com/rur/good/baseline/page/page/newpage"
)

// Code generated by go generate; DO NOT EDIT.

func registerPages(hlp page.Helper, exec treetop.ViewExecutor) {
	// register pages
	example.Routes(hlp, exec)
	newpage.Routes(hlp, exec)
}
