package main

import (
	"github.com/rur/good/baseline/starter_test/page"
	"github.com/rur/treetop"

	"github.com/rur/good/baseline/starter_test/page/intro"
	"github.com/rur/good/baseline/starter_test/page/newpage"
)

// Code generated by go generate; DO NOT EDIT.

func registerPages(hlp page.Helper, exec treetop.ViewExecutor) {
	// register pages
	intro.Routes(hlp, exec)
	newpage.Routes(hlp, exec)
}
