package example

import (
	"github.com/rur/good/baseline/routes_test/page"
	"github.com/rur/treetop"
)

func Routes(hlp page.Helper, exec treetop.ViewExecutor) {

	// Code generated by go generate; DO NOT EDIT.

	example := treetop.NewView(
		"page/example/templates/example.html.tmpl",
		hlp.BindEnv(bindResources(exampleHandler)),
	)

	// [[content]]
	examplePlaceholder := example.NewDefaultSubView(
		"content",
		"page/example/templates/content/placeholder.html.tmpl",
		hlp.BindEnv(bindResources(placeholderHandler)),
	)

	// [[content.form]]
	placeholderForm := examplePlaceholder.NewDefaultSubView(
		"form",
		"page/example/templates/content/placeholder.html.tmpl",
		treetop.Constant("TODO"),
	)

	// [[content]]
	alternativeContent := example.NewSubView(
		"content",
		"page/example/templates/content/placeholder.html.tmpl",
		hlp.BindEnv(bindResources(placeholderHandler)),
	)
	settings := example.NewSubView(
		"content",
		"page/example/templates/content/settings.html.tmpl",
		hlp.BindEnv(bindResources(settingsHandler)),
	)

	// [[content.settings]]
	generalSettingsTab := settings.NewSubView(
		"settings",
		"page/example/templates/content/settings/general-settings-tab.html.tmpl",
		hlp.BindEnv(bindResources(generalSettingsTabHandler)),
	)
	advancedSettingsTab := settings.NewSubView(
		"settings",
		"page/example/templates/content/settings/advanced-settings-tab.html.tmpl",
		hlp.BindEnv(bindResources(advancedSettingsTabHandler)),
	)

	// [[content.tabs]]
	settings.NewDefaultSubView(
		"tabs",
		"page/example/templates/content/tabs/other-tabs.html.tmpl",
		treetop.Constant("Hello World"),
	)

	// [[scripts]]
	example.NewDefaultSubView(
		"scripts",
		"page/templates/scripts.html.tmpl",
		treetop.Noop,
	)

	// [[site-nav]]
	example.NewDefaultSubView(
		"site-nav",
		"page/templates/nav.html.tmpl",
		hlp.BindEnv(page.SiteNavHandler),
	)

	hlp.Handle("/example",
		exec.NewViewHandler(examplePlaceholder))
	hlp.HandlePOST("/example/form",
		exec.NewViewHandler(placeholderForm).FragmentOnly())
	hlp.Handle("/example/alt",
		exec.NewViewHandler(alternativeContent).PageOnly())
	hlp.Handle("/example/settings",
		exec.NewViewHandler(generalSettingsTab))
	hlp.Handle("/example/advanced-settings",
		exec.NewViewHandler(advancedSettingsTab))

}
