_ref = "example"
_template = "page/example/templates/example.html.tmpl"
_handler = "hlp.BindEnv(bindResources(exampleHandler))"
_doc = "Base HTML template for example page"
_uri = "/example"

    [[site-nav]]
    _ref = "main-nav"
    _default = true
    _template = "page/templates/nav.html.tmpl"
    _handler = "hlp.BindEnv(page.SiteNavHandler)"

    [[content]]
    _ref = "example-placeholder"
    _template = "page/example/templates/content/example-placeholder.html.tmpl"
    _default = true
    _doc = "Placeholder page"
    _partial = true
    _path = "/example"
    _handler = 'treetop.Delegate("form")'

        [[content.form]]
        _ref = "placeholder-form"
        _template = "page/example/templates/content/form/placeholder-form.html.tmpl"
        _handler = "hlp.BindEnv(bindResources(placeholderFormHandler))"
        _default = true
        _doc = "Placeholder form"
        _fragment = true
        _method = "POST"
        _path = "/example/form"

    [[content]]
    _ref = "alternative-content"
    _template = "page/example/templates/content/alternative-content.html.tmpl"
    _handler = "hlp.BindEnv(bindResources(alternativeContentHandler))"
    _doc = "Alaternative Content Page"
    _path = "/example/alt"

    [[content]]
    _ref = "settings-layout"
    _template = "page/example/templates/content/settings-layout.html.tmpl"
    _handler = "hlp.BindEnv(bindResources(settingsLayoutHandler))"
    _doc = "Settings page layout"

        [[content.tabs]]
        _ref = "settings-tabs"
        _template = "page/example/templates/content/tabs/settings-tabs.html.tmpl"
        _doc = "Tabs for the settings page content"
        _default = true
        _handler = 'treetop.Constant("Hello World")'

        [[content.settings]]
        _ref = "general-settings"
        _template = "page/example/templates/content/settings/general-settings.html.tmpl"
        _handler = "hlp.BindEnv(bindResources(generalSettingsHandler))"
        _doc = "General settings area"
        _path = "/example/settings"
        _partial = true

        [[content.settings]]
        _ref = "advanced-settings"
        _template = "page/example/templates/content/settings/advanced-settings.html.tmpl"
        _handler = "hlp.BindEnv(bindResources(advancedSettingsHandler))"
        _doc = "Advanced settings area"
        _path = "/example/advanced-settings"
        _partial = true

            [[content.settings.settings-form]]
            _ref = "update-advanced-settings"
            _template = "page/example/templates/content/settings/settings-form/update-advanced-settings.html.tmpl"
            _handler = "hlp.BindEnv(bindResources(updateAdvancedSettingsHandler))"
            _doc = "Accept update to advanced settings and show result"
            _path = "/example/advanced-settings/submit"
            _fragment = true
            _method = "POST"

    [[scripts]]
    _ref = "site-scripts"
    _default = true
    _template = "page/templates/scripts.html.tmpl"
    _handler = "treetop.Noop"
