package example

import (
	"github.com/rur/good/baseline/routes_test/page"
	"github.com/rur/treetop"
)

func Routes(hlp page.Helper, exec treetop.ViewExecutor) {

	// Code generated by go generate; DO NOT EDIT.

	example := treetop.NewView(
		"page/example/templates/example.html.tmpl",
		hlp.BindEnv(bindResources(exampleHandler)),
	)

	// [[content]]
	examplePlaceholder := example.NewDefaultSubView(
		"content",
		"page/example/templates/content/example-placeholder.html.tmpl",
		treetop.Delegate("form"),
	)

	// [[content.form]]
	placeholderForm := examplePlaceholder.NewDefaultSubView(
		"form",
		"page/example/templates/content/form/placeholder-form.html.tmpl",
		hlp.BindEnv(bindResources(placeholderFormHandler)),
	)

	// [[content]]
	alternativeContent := example.NewSubView(
		"content",
		"page/example/templates/content/alternative-content.html.tmpl",
		hlp.BindEnv(bindResources(alternativeContentHandler)),
	)
	settingsLayout := example.NewSubView(
		"content",
		"page/example/templates/content/settings-layout.html.tmpl",
		hlp.BindEnv(bindResources(settingsLayoutHandler)),
	)

	// [[content.settings]]
	generalSettings := settingsLayout.NewSubView(
		"settings",
		"page/example/templates/content/settings/general-settings.html.tmpl",
		hlp.BindEnv(bindResources(generalSettingsHandler)),
	)
	advancedSettings := settingsLayout.NewSubView(
		"settings",
		"page/example/templates/content/settings/advanced-settings.html.tmpl",
		hlp.BindEnv(bindResources(advancedSettingsHandler)),
	)

	// [[content.settings.settings-form]]
	updateAdvancedSettings := advancedSettings.NewSubView(
		"settings-form",
		"page/example/templates/content/settings/settings-form/update-advanced-settings.html.tmpl",
		hlp.BindEnv(bindResources(updateAdvancedSettingsHandler)),
	)

	// [[content.tabs]]
	settingsLayout.NewDefaultSubView(
		"tabs",
		"page/example/templates/content/tabs/settings-tabs.html.tmpl",
		treetop.Constant("Hello World"),
	)

	// [[scripts]]
	example.NewDefaultSubView(
		"scripts",
		"page/templates/scripts.html.tmpl",
		treetop.Noop,
	)

	// [[site-nav]]
	example.NewDefaultSubView(
		"site-nav",
		"page/templates/nav.html.tmpl",
		hlp.BindEnv(page.SiteNavHandler),
	)

	hlp.Handle("/example",
		exec.NewViewHandler(examplePlaceholder))
	hlp.HandlePOST("/example/form",
		exec.NewViewHandler(placeholderForm).FragmentOnly())
	hlp.Handle("/example/alt",
		exec.NewViewHandler(alternativeContent).PageOnly())
	hlp.Handle("/example/settings",
		exec.NewViewHandler(generalSettings))
	hlp.Handle("/example/advanced-settings",
		exec.NewViewHandler(advancedSettings))
	hlp.HandlePOST("/example/advanced-settings/submit",
		exec.NewViewHandler(updateAdvancedSettings).FragmentOnly())

}
