_ref = "newpage"
_doc = "Base HTML template for newpage page"
_entrypoint = "/newpage"
_template = "page/newpage/templates/base.html.tmpl"

    [[nav]]
    _ref = "page-nav"
    _default = true

    [[content]]
    _ref = "page-landing"
    _default = true
    _doc = "Landing content view for the newpage page URI"
    _method = "GET"
    _path = "/newpage"

    [[styles]]
    _ref = "site-styles"
    _default = true
    _doc = "Include page styles in document header"
    _template = "page/newpage/templates/styles.html.tmpl"
    _handler = "treetop.Noop"

    [[scripts]]
    _ref = "site-scripts"
    _default = true
    _doc = "Include page scripts"
    _template = "page/newpage/templates/scripts.html.tmpl"
    _handler = "treetop.Noop"
