package main

import (
	"github.com/rur/good/_baseline/site/page"
	"github.com/rur/treetop"

	"github.com/rur/good/_baseline/site/page/example"
)

// Code generated by go generate; DO NOT EDIT.

func registerPages(hlp page.Helper, exec treetop.ViewExecutor) {
	// register pages
	example.Routes(hlp, exec)
}
