package main

import (
	"github.com/rur/good/_baseline/site/page"
	"github.com/rur/treetop"

	"encoding/json"

	"github.com/rur/good/_baseline/site/page/example"
	"github.com/rur/good/_baseline/site/service"
)

// Code generated by go generate; DO NOT EDIT.

func registerPages(hlp page.Helper, exec treetop.ViewExecutor) {
	// register pages
	example.Routes(hlp, exec)
}

var (
	sitemap  service.Sitemap
	siteinfo = `
{
	"example": {
		"uri": "/example",
		"routes": {
			"placeholder": {
				"block": "content",
				"path": "/example/placeholder"
			}
		}
	},
	"testing": {
		"uri": "/testing",
		"routes": {
			"placeholder": {
				"block": "content",
				"path": "/testing/placeholder"
			}
		}
	}
}`
)

func init() {
	err := json.Unmarshal([]byte(siteinfo), &sitemap)
	// prevent server from starting
	if err != nil {
		panic(err)
	}
}
