_namespace = "github.com/rur/good/_baseline/site"
_page = "settings"
_template = "page/templates/base.html.tmpl"
_handler = "hlp.BindEnv(page.BaseHandler)"
_doc = "Base HTML template for settings page"
_uri = "/settings"

    [[content]]
    _name = "settings-placeholder"
    _default = true
    _doc = "Placeholder page"
    _path = "/settings"
    _template = "page/settings/templates/placedholder.html.tmpl"
    _handler = "env.Bind(bindResources(placedholderHandler))"
